### ISSUE TITLE
Searching on admin teams page does not filter on hashid

### ISSUE THREAD

**Issue by hardillb** [FlowFuse/flowfuse#1375]
### Current Behavior

Searching the table only matches the team name

### Expected Behavior

Be able to search on both name and hashid

### Steps To Reproduce

Login as admin
open team list
try to search by hashid

### Environment

- FlowForge version: 1.1.0
- Node.js version: 16.x
- npm version: 8.x
- Platform/OS: All
- Browser: All

**Comment by Pezmc** [comment]
@hardillb and I looked into this briefly yesterday and there are two related causes:

 - Client side search is disabled for the teams table, only server side search happens - since https://github.com/flowforge/flowforge/pull/1110
 - Server side search only searches a subset of fields, which are set on a [per model basis](https://github.com/flowforge/flowforge/blob/ad2bb54e2a33846712dbf4a525645730e687f0f6/forge/db/models/Team.js#L181), it does not respect the `search-fields` prop, which is only for client side search

There's an issue for a more generic improvement to server search https://github.com/flowforge/forge-ui-components/issues/101; but this specific issue could be solved by adjusting the columns the server side searches.

**Comment by knolleary** [comment]
Fixed via https://github.com/FlowFuse/flowfuse/pull/4584
