### ISSUE TITLE
On FlowForge Cloud, how to install an external node which is not available in Node-RED library? 

### ISSUE THREAD

**Issue by lianshengleo27** [FlowFuse/flowfuse#1890]
### Description

I have just started using FlowForge Cloud and had no problems installing node modules from `Manage Palette` or via `Setting → Palette → Installed Modules` on FlowForge Cloud Dashboard. 

However, I just had a customerized node which I would like to use on FlowForge Cloud, but since I cannot access the root directory (`~/.node-red`) and thereby not possible to install the node by `npm install <pkg-name>`. 

Could anyone give me some ideas? Many thanks.

**Comment by biancode** [comment]
It would help to be able to send some .npmrc to the node-red container, which just enables the admin to give private nodes via FlowForge for installation (Installed Modules).

**Comment by MarianRaphael** [comment]
Thank you for bringing up this issue and providing valuable feedback. We already have an epic tracking the possibility of custom node catalogues here: Custom Node Catalogues #217. The scope of the epic includes providing a "custom catalog" to users, which could be in addition to or instead of the standard registry. This could address the need for installing customized nodes on FlowForge Cloud. Please feel free to share any additional thoughts or concerns you may have and vote for the issue, as this makes it easier for us to have an overview.

**Comment by joepavitt** [comment]
#217 covers this requirement - so will close the issue. Any problems, please re-open @lianshengleo27
