### ISSUE TITLE
[DB] Migration scenario during upgrade: migration failure, the system couldn't recover automatically

### ISSUE THREAD

**Issue by elenaviter** [FlowFuse/flowfuse#2803]
### Description of a problem
During upgrade from `1.7.0` to `1.11.3`, one of the patches ([20230504-01-add-pipelines.js](https://github.com/flowforge/flowforge/blob/main/forge/db/migrations/20230504-01-add-pipelines.js)) was written to `MetaVersions` table as if it was applied while it wasn't in fact.
Because of this, FlowFuse couldn't start since the DB upgrade activity failed (couldn't apply the next patch in the list because the tables entered by `20230504-01-add-pipelines.js` were missing).

### How the case was resolved 
- via manual intervention to `MetaVersions` table and deleting the entry with `20230504-01-add-pipelines.js` from there. 
- restart FlowFuse to start the DB upgrade job over. With second attempt the DB Job was able to run all needed patches and complete the upgrade. 

### Expected Behavior

The changes applied by the patches are verified before the patch is concluded as applied and written to `MetaVersions` table.

### Steps To Reproduce

Not sure it can be easily reproduced.
This was reproduced once, it was an upgrade `1.7.0` -> `1.11.3` of k8s-based FlowFuse deployed with the [Helm](https://github.com/flowforge/helm/tree/main/helm/flowforge) - e.g. with "in-house" Postgres. 
We had 1 more upgrade `1.7.0` -> `1.11.3` before this one, and it succeeded. 
We had many more upgrades before between other versions and yet it's for the first time when the DB migration failed. 

### Environment

- FlowForge version: 1.11.3
- Node.js version: 16.20.2
- npm version: 8.19.4
- Platform/OS: Alpine Linux v3.18
- Browser: -

### Have you provided an initial effort estimate for this issue?

I am not a FlowForge team member

**Comment by MarianRaphael** [comment]
Thank you for bringing this issue to our attention.

**Comment by elenaviter** [comment]
Hello @MarianRaphael.
The same problem happened again. 
This time during attempt of **upgrade** from 1.11.3 to 1.13.0.
Since the problematic change (`20230504-01-add-pipelines.js`) was introduced before 1.11.3, the fact that it broke upgrade  1.11.3 -> 1.13.0 means that during **clean installation** of 1.11.3 (and it was indeed a 'clean' installation, on a clean env), the patches starting from `20230504-01-add-pipelines.js` (at minimal) were not applied.

**Comment by ggworld** [comment]
@knolleary - hello, this PROBLEM is refacing on many Flowfuse upgrades we perform can you pls. evaluate and react

**Comment by hardillb** [comment]
Looking now

**Comment by hardillb** [comment]
Can reproduce with sqlite, looking at the failing migration.

**Comment by hardillb** [comment]
I've just run a clean 1.7.0 -> 1.11.3 -> 1.13.0 upgrade so this might be a race condition somewhere. Will keep digging.

**Comment by hardillb** [comment]
OK, I think I understand the problem. It's and interaction of ee vs none ee installs. Will discuss with @knolleary when my flight gets in.

**Comment by knolleary** [comment]
I think I've got to the bottom of it as well. Not yet caught up with @hardillb to compare notes, however here's my analysis.

When FF starts up it checks the db for the `MetaVersions` table. If there are no other tables present, we know this is a clean start. We allow Sequelize to create all the tables it needs itself, so we do not apply any migrations. We update the `MetaVersions` table to mark all of the migrations as 'done' as we expect Sequelize to initialise everything into that state.

Now, the problem comes with the EE code. This code is only loaded if the platform is running with an EE license. We have a number of models that are part of the EE code base. Without an EE license, that code isn't loaded, so Sequelize doesn't know about those models and doesn't create the tables.

This leaves us without the EE database tables in place - so any subsequent migration that assumes the tables are present are going to fail.

The immediate fix will be to update *any* existing migration that touches an EE-only model and have it ensure the corresponding table exists first. But we really need to be careful to get things where they are expected to be.

I *think* this primarily applies to the Pipeline models, however this situation could happen whenever we introduce a new EE-only model. If we introduce a new EE-only model in version X, then any user who does a clean install of version X and runs *without* an EE license, will not get that table created. So we need a solution to fix this up for existing installs, but also improve our strategy for handling this moving forwards.

I will work on a fix on Tuesday.

**Comment by knolleary** [comment]
I have raised https://github.com/FlowFuse/flowfuse/pull/3033 with an initial fix for the specific scenario originally mentioned in the issue. There is a wider issue in terms of how we handle this is a few other scenarios, but I'm still thinking about how to describe them.

**Comment by ggworld** [comment]
@knolleary - will the fix enable us to perform upgrade ? we have couple of thinks in the queue after it

**Comment by knolleary** [comment]
@ggworld we believe so based on our local testing. It will be included in this week's maintenance release later today.

**Comment by hardillb** [comment]
@ggworld & @elenaviter Can we close this now?

**Comment by elenaviter** [comment]
Hello @knolleary, @hardillb,

We have successfully verified the upgrade `1.11.3` -> `1.13.2` on two of our systems, and everything worked smoothly. 
I want to extend our gratitude for your prompt and effective efforts in addressing the issue!

This issue has been resolved, so I'll be closing it now. Thank you once again for your support!
