### ISSUE TITLE
UX around devices in devops pipelines

### ISSUE THREAD

**Issue by Pezmc** [FlowFuse/flowfuse#2902]
### Related Issue

#2756

### Description

Today, devices are assigned to pipeline stages via instances i.e. a device is assigned to a instance, and an instance is assigned to a pipeline stage.

In https://github.com/FlowFuse/flowfuse/issues/2756 we're introducing support for a single device to be tied to a pipeline stage without going via an instance.

Longer term, but not part of this release but we should take it into account, multiple devices will be able to be assigned to pipeline stages (possible via a tag - #2655). 

We need decide on how this will work for the user; including:

 - When creating a pipeline stage, they should now be able to select a single device or an instance
 - The stage UI needs to be updated to show the device OR instance (and clearly differentiate between the two)
 - Anywhere in the pipeline stage references instance now needs to consider it being linked to a device instead

**Comment by Pezmc** [comment]
There's a very very rough UI in https://github.com/FlowFuse/flowfuse/pull/3024. We need to think about how to make this concept of devices being able to be assigned to pipeline stages easiest for a user to understand.

**Comment by Yndira-FlowForge** [comment]
@Pezmc Please refresh my memory: Can you have both a device and an instance at the same time in a pipeline stage? In the description of the issue, it seems like it's one or the other. When we discussed the toggle, that's what I was thinking. But now I see this in the screenshot you shared, and I'm not so sure anymore.
<img width="269" alt="Screenshot 2023-11-08 at 14 01 25" src="https://github.com/FlowFuse/flowfuse/assets/129537638/bbc9cca7-866b-4fd9-a212-53e37975f8ab">

**Comment by Pezmc** [comment]
@Yndira-FlowForge And I spoke on slack and we re-confirmed that a stage can have a device **or** an instance but not both.

**Comment by Yndira-FlowForge** [comment]
Great, thanks @Pezmc!

**Comment by Yndira-FlowForge** [comment]
Ok, so this is what I got
1. A toggle to choose the stage type (instance or device) that changes color depending on the selection (there's a reason for this in the next step)
![Application - Instances](https://github.com/FlowFuse/flowfuse/assets/129537638/3dc4ce23-66cc-4340-8c36-afad093d17c4)
![Application - Instances - dev](https://github.com/FlowFuse/flowfuse/assets/129537638/780efc25-d027-4965-8d0e-f53c9e47f756)

2.1 Added icons next to "instance" and "device" in each stage card.
2.2 The "active one" has the same color code as the toggle, creating a visual connection to the previous step.
2.3 The other one is greyed out, indicating that it's possible to create or change the stage type, but it remains clear which type it currently is.
2.4 All text on the right side of each card is now aligned to the right for easier text navigation.
2.5 All cards are the same height as the largest one and have the same width.
2.6 The "add stage" is narrower, providing more space for the rest of the cards.
2.7 The last chevron is also greyed out, as there is no actual stage next to it.

![Application - Instances-1](https://github.com/FlowFuse/flowfuse/assets/129537638/133fd180-9c21-4a92-89cb-d15bd86055e9)

I think the dark red makes sense because it's the same color as the Node-RED logo, and an instance is the Node-RED project. However, I still have some doubts about whether this might be mistaken for an alert or error.

@joepavitt what do you think? I've already shared it with @Pezmc and these versions have his feedback implemented.

**Comment by joepavitt** [comment]
> 1. A toggle to choose the stage type (instance or device) that changes color depending on the selection (there's a reason for this in the next step)

Not a fan of the toggle button switch with Instance/Device. We'll almost immediately be switching this over to a three option decision, so I'd rather re-use some of the existing tile selection component if we want to go down that route. That design feels a little out of place. This also gives a little real estate to provide a description of the option in case it's not intuitive at first.

> 2.4 All text on the right side of each card is now aligned to the right for easier text navigation.

We're likely to need to have multiple lines for the label/value, whilst my design had sngle line, in practice, names/urls are very long, and make text truncation a real pain to deal with.

> 2.5 All cards are the same height as the largest one and have the same width.

I understand the visual appeal of this, but in reality, it then forces us to include a lot of unnecessary data (e.g. options that aren't used). For the pipeline stages, I don't think we need to show the semi-transparent text, just the options that exist for that Stage.

> 2.6 The "add stage" is narrower, providing more space for the rest of the cards.

What happens with just 2 stages, still narrower? What happens with 4 stages? Think keeping it consistent in size will be far easier to build.

> I think the dark red makes sense because it's the same colour as the Node-RED logo, and an instance is the Node-RED project. However, I still have some doubts about whether this might be mistaken for an alert or error.

Understood, I do really like the colours though. Can have a play once it's live to see if any variations look nicer, but I'm happy with the colour choices here.

**Comment by Yndira-FlowForge** [comment]
Hi @joepavitt thanks for the feedback :ok_hand:

Using cards instead of the toggle would look like this:
![Pipelines - Stage settings](https://github.com/FlowFuse/flowfuse/assets/129537638/754dad98-74d6-4905-8ab0-ebb1624384ef)

> 2.5 All cards are the same height as the largest one and have the same width.

> I understand the visual appeal of this, but in reality, it then forces us to include a lot of unnecessary data (e.g. options that aren't used). For the pipeline stages, I don't think we need to show the semi-transparent text, just the options that exist for that Stage.

I thought this could indicate that it's possible to change the stage type while making clear which type it currently is.

Also, it would help maintain some kind of order so that the same value would always be in the same position on every card, as devices don't have URLs or another label/value that replaces it.

If we want to show only available options for each stage, would it make sense to make the URL the last one? So everything else would keep its position across every card (except for the last stage, which doesn't have a "deploy action").

It would look like this (and still same height, just no data in the last "slot(s)":
![Pipelines - 3 stages](https://github.com/FlowFuse/flowfuse/assets/129537638/d6ca1605-5f4b-4135-b69b-04a7cb49e9a6)


> What happens with just 2 stages, still narrower? What happens with 4 stages? Think keeping it consistent in size will be far easier to build.

It could be the same width from 0 to 2 stages
![Pipelines - from none to 2 stages](https://github.com/FlowFuse/flowfuse/assets/129537638/4862de12-18bf-4ef1-88d7-47a3b0fdb378)

And from 3 onwards, narrower
![Pipelines - 3 stages](https://github.com/FlowFuse/flowfuse/assets/129537638/3cc47f6d-e0d1-4d54-926d-00021f7116fe)
![Pipelines - 4 stages](https://github.com/FlowFuse/flowfuse/assets/129537638/3e2c1df7-1050-439f-97a6-96645dbc6e4d)

And you're right, keeping it consistent would be easier—maybe as a future iteration or a different approach? It's just that the alignment looks off, and the values are sometimes so long that it seems like a waste of space having the blank one the same width as the rest of them... It currently looks like this:

<img width="1241" alt="Screenshot 2023-11-14 at 13 50 35" src="https://github.com/FlowFuse/flowfuse/assets/129537638/569316c9-870e-4c3c-a695-b3542f356802">

At the end of the day, just having the tile selection component in the stage settings screen and the icons next to device or instance would solve the "problem" we had, the rest were merely suggestions that I thought could improve readability, and I understand they are not the priority in this task 😉

**Comment by joepavitt** [comment]
> Using cards instead of the toggle would look like this:

We can look at modifying the component though to colour/style as per the icons you've provided, so replace the ticks with the instance/device icon and colour?

> If we want to show only available options for each stage, would it make sense to make the URL the last one? So everything else would keep its position across every card (except for the last stage, which doesn't have a "deploy action").

Great idea, although not sure we still need the empty whitespace below it to force the heights to be the same.

> And from 3 onwards, narrower

And 5/6/7 stages? We cant just narrow the stage width each time, at that point, it has to become scrollable in the x-axis.

**Comment by Yndira-FlowForge** [comment]
> We can look at modifying the component though to colour/style as per the icons you've provided, so replace the ticks with the instance/device icon and colour?

Sure!
![Pipelines - Stage settings](https://github.com/FlowFuse/flowfuse/assets/129537638/7f3cde81-bd5b-4559-8c22-d9d7736e9c6d)
<img width="491" alt="Screenshot 2023-11-14 at 14 30 08" src="https://github.com/FlowFuse/flowfuse/assets/129537638/b24248b8-06a5-4a80-843d-c710527e318b">

> And 5/6/7 stages? We cant just narrow the stage width each time, at that point, it has to become scrollable in the x-axis.

For sure, that's the current behaviour, nothing against that!

Here's the Figma file in case you want to play with it; or, if it's ok, @Pezmc you could access it in case you need any assets from there.

**Comment by joepavitt** [comment]
@Yndira-FlowForge thoughts?

<img width="841" alt="Screenshot 2023-11-16 at 11 54 45" src="https://github.com/FlowFuse/flowfuse/assets/99246719/c9cb17e0-87aa-41da-b8bc-d99b7ac48993">

**Comment by Yndira-FlowForge** [comment]
I think the "instance" and "device" words might be too small to read. Do you think the icons are obvious enough?

**Comment by joepavitt** [comment]
> Do you think the icons are obvious enough?

I think so

**Comment by Yndira-FlowForge** [comment]
Good idea! Maybe even remove those words? It could be frustrating if people find them hard to read.

**Comment by joepavitt** [comment]
what it looks like for "real":

<img width="1728" alt="Screenshot 2023-11-16 at 12 22 17" src="https://github.com/FlowFuse/flowfuse/assets/99246719/41ca4b12-b0df-474c-aa0d-19f60137e712">

**Comment by Yndira-FlowForge** [comment]
I can read it, but it still seems small. Additionally, the icon is smaller than in the design, and the text isn't aligned with the top of the icon due to space constraints. If we intend to keep the label, I suggest enlarging the icon.
_(I still struggle with all the varying card sizes hehe)_

**Comment by joepavitt** [comment]
>  Additionally, the icon is smaller than in the design,

It's using our default 20px icon size atm - used across the whole app.

> and the text isn't aligned with the top of the icon due to space constraints

It is centrally aligned vertically, although I think the line-height of the Instance name makes it look a little funky.

> (I still struggle with all the varying card sizes hehe)

It looks a lot better than having consistent sizes with unnecessary empty space.

**Comment by joepavitt** [comment]
Actually, you're right

<img width="1235" alt="Screenshot 2023-11-16 at 12 49 39" src="https://github.com/FlowFuse/flowfuse/assets/99246719/720fe550-fc74-4431-9370-6e9b712c751b">

**Comment by joepavitt** [comment]
Played a little more with spacing, and came to this:

<img width="1025" alt="Screenshot 2023-11-16 at 16 47 19" src="https://github.com/FlowFuse/flowfuse/assets/99246719/628649c7-f8f6-4c57-ae67-f0a4fbeeaae6">

**Comment by Yndira-FlowForge** [comment]
It looks so much better! 😍

**Comment by Yndira-FlowForge** [comment]
Are you going to put the URL at the bottom of the cards?

**Comment by Pezmc** [comment]
Closing this out as the design is complete and it was implemented in https://github.com/FlowFuse/flowfuse/pull/3024, thank you @Yndira-FlowForge and @joepavitt!

**Comment by joepavitt** [comment]
@GogoVega very valid request - can you open a new issue/request please, and then link to it here?
