### ISSUE TITLE
Project Nodes unavailable on a Device assigned to an Application

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#3018]
### Current Behavior

When a Device is assigned to an Application, not an instance, the Project nodes are unavailable.

This is because the Project Nodes expect to be operating within the context of an instance in order to establish the proper ACL checks.

This is not a regression - this has been a limitation since the ability to assigned devices to Applications was introduced. However it needs to be addressed as users expect to use the Project Nodes regardless.

### Expected Behavior

The Project Nodes should be available to Application-assigned devices

### Steps To Reproduce

 - Assign device to Application
 - Put in developer mode
 - open editor - note lack of Project nodes

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Steve-Mcl** [comment]
@knolleary 

What I have working thus far:

1. App Assigned Device can broadcast (and other instances / devices) can receive them
2. App Assigned Device can send direct to an instance (that instance can of course be an instance assigned device) 
3. Can perform link-call to an instance 


https://github.com/FlowFuse/flowfuse/assets/44235289/d52a3ca3-c6f4-4143-9415-e3e8352f13e1




Missing functionality:
1. An instance or other device CANNOT send direct to an App Assigned Device
2. An instance or other device CANNOT link-call to an App Assigned Device


Having had a bit of a chew on getting to this point (dev env issues, debugging issues, etc) I must apologise for forgetting the exact details of our chat last Monday. That leads to the question:

Is it enough in this iteration to support the "working set" (as listed in the first 3 points) - OR - is it desirable to get the "missing functionality" implemented too?

---

CC @MarianRaphael ^

**Comment by knolleary** [comment]
The goal is a minimal set of functionality that starts filling the gap caused by the absence of the project nodes in an App-assigned device.

Lets get what you've done so far into a PR so we can start reviewing. We need to make sure the MQTT topic structures are appropriate and your video doesn't show anything about how these new options are exposed in the UI.

We will want to be able to messaging directed at the Device, but that can be a second iteration.

**Comment by Steve-Mcl** [comment]
> We need to make sure the MQTT topic structures are appropriate

There are no changes to the topic structure. That may be necessary to support direct device messaging. And as I move onto supporting direct device messaging I may even discover we have locked ourselves into a less than extensible format.  However there is always the `V1` topic section to fix that if necessary. 

> your video doesn't show anything about how these new options are exposed in the UI

There are no changes to the UI for the current level of support I listed in the first 3 points. However as allude to next, I believe that may be necessary (or rather highly desirable)


> We will want to be able to messaging directed at the Device, but that can be a second iteration

Understand.  

There is a fair bit of design discussion required around direct to device messaging that needs to be understood. For example, we currently show the user a dropdown list of instances. If we simply add devices to this list, larger users will find the UX pretty uncomfortable.  Next there is the scoping - e.g. would we even want to list devices in different applications along side devices in this application. Finally there is making the project nodes application aware. 

I think a short brainstorming session would really help with the remaining pieces.

**Comment by Steve-Mcl** [comment]
> > your video doesn't show anything about how these new options are exposed in the UI
> 
> There are no changes to the UI for the current level of support

Correction. There are minimal wording changes to the UI and help to indicate devices are now ☺️

**Comment by knolleary** [comment]
Reopening as there are multiple PRs needed to land for this to be complete.

**Comment by Steve-Mcl** [comment]
Following the **Verification** procedure written up in [this PR](https://github.com/FlowFuse/flowfuse/pull/3074#issue-1993088486), I have confirmed it works as expected.


https://github.com/FlowFuse/flowfuse/assets/44235289/c8ddb8fd-62d7-4876-a8d1-b7bd3425f113




Points of note:

1. A device sat in dev mode will NOT be instructed to update (switching out of dev mode will cause the difference in modules to be detected and thus update
2. On an app owned device, the Project In node might not be as clear as it could be.
   ![image](https://github.com/FlowFuse/flowfuse/assets/44235289/89e7191f-442e-4bae-ac8f-f18f8686c716)
   Additional context: App assigned devices can not be chosen as a target in the Project-out node at in this 1st iteration.
   This option being enabled may cause a user to go looking for "how to send direct message#" (or report an issue)
   We might want to consider disabling this option in an app owned device
3. An already created instance needed to be restarted before it would respond to a `link-call` (was getting `"Project Link Source not valid"`) which suggested there was something wrong with the `messageEvent` object. I thoroughly checked the data in the `msg` and all appeared correct.  I came to the conclusion that the instance needed a restart in order to load latest project nodes - doh.  But it tripped me up for some time - not certain how we can handle this kind of situation?

RE Point 2 - I will raise an issue and PR before launch. (discussed here: https://flowforgeworkspace.slack.com/archives/C032Q63FGG1/p1700682292559729)
