### ISSUE TITLE
Stripe will invoice and charge for teams that have already been deleted

### ISSUE THREAD

**Issue by zackwasli** [FlowFuse/flowfuse#3020]
### Current Behavior

Stripe can invoice you for teams that have been deleted for a long period of time. 

### Expected Behavior

If there's a charge we need to charge it right away upon deletion.

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by knolleary** [comment]
Checking our code, I can see that when a Team is deleted, we tell stripe to delete the Team subscription and we set the `invoice_now` flag to true which is expected to generate a final invoice. From reading the docs, it isn't entirely clear whether that invoice is sent immediately, or at the end of the current billing cycle. If the latter, then I could see how that could lead to a gap in time between deleting a team and receiving that final invoice.

I presume this issue is in response to a specific customer incident. Can you provide me details via a private channel so I can examine what happened?

**Comment by knolleary** [comment]
Based on the evidence provided, this appears to be a 'expected' case that a team was created, an instance created within it, then everything was deleted. At the time of deletion, the invoice was finalised and sent. There was no long delay involved.
