### ISSUE TITLE
(Device Agent) Start/Restart/Suspend Device from FF editor

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#3292]
### Discussed in https://github.com/orgs/FlowFuse/discussions/3279

<div type='discussions-op-text'>

<sup>Originally posted by **GogoVega** January  1, 2024</sup>
Hi,
Is it planned to be able to control the NR instance on a device from the FF editor?</div>

## Current Situation
Currently, FlowFuse hosted instances offer the ability to Start/Restart/Suspend the Node-RED runtime. However, this functionality is not available for devices. 

## User Story
As a FlowFuse user, I want the functionalities to Start/Restart/Suspend a device directly from the FlowFuse interface. This feature would eliminate the need for manual connecting and restarting of the complete device-agent service.

## License
CE 
Starter, Teams and Enterprise-Tier

**Comment by MarianRaphael** [comment]
Requested by https://app-eu1.hubspot.com/contacts/26586079/record/0-2/8342532829

**Comment by Steve-Mcl** [comment]
@MarianRaphael @joepavitt 

Are there any UX/UI designs for this?



## For example: where would we place the options:

### Current Device top row:
![Image](https://github.com/FlowFuse/flowfuse/assets/44235289/a40ad40a-c278-4108-92c3-07460ac9bc06)

### If we simply add the <kbd>Actions</kbd> it gets even more crowded and more likely to do that odd wrapping:
![Image](https://github.com/FlowFuse/flowfuse/assets/44235289/748e4cc6-9ccf-48e6-83ee-a80e7fc8ff9c)

* Would we want to move the toggle into the dropdown?
* Perhaps alternatively, we move the developer mode toggle somewhere else (to align with instances?)


## Regarding functionality:
* Would we expect the device agent to "remember" it was suspended (like an instance does)
* If the users Device Agent has not been updated (for this new funtionality) would we simply hide the actions OR alert the user they need to update the agent (kinda prompt / reminder that new functionality exists)?

**Comment by Steve-Mcl** [comment]
Additional question:

Will we expect the device agent to still check in when suspended? 
* If we dont, the status of the device in FF will get a `red` "last seen" badge clocking up
* If we do, there is potentially nnn devices checking in that are in suspended mode.
  * however, we could reduce the checkin frequency.
  * IMO, this is the better option as it give _truer_ state to the platform

**Comment by Steve-Mcl** [comment]
Additional questions:

Can we clarify the meaning of the `suspend` state in context of the device agent?

Taking into consideration the Device Agent is a remote process (be that a process running on edge or in docker or as a server service etc), in order to be started, the Device Agent itself will need to be "kept running" (in order to satisfy a `start` command) so the `suspend` operation surely just "stops" the launcher (agent continues to live).  

<br>

Additionally, in the case of there being no MQTT broker (i.e. when the device agent is using HTTP polling) these operations will be far from responsive and would rely on the Device Agent checking in. This would result in sub-optimal UX and confusion for the user.  How are we to handle this?

**Comment by MarianRaphael** [comment]
> Are there any UX/UI designs for this?

If Joe does not veto it, simply adding the Actions button is what I had in mind.

> Will we expect the device agent to still check in when suspended?

Yes

> Can we clarify the meaning of the suspend state in context of the device agent?

As you said, the Device Agent itself will need to be "kept running" it's about the Node-RED instance

**Comment by MarianRaphael** [comment]
> Additionally, in the case of there being no MQTT broker (i.e. when the device agent is using HTTP polling) these operations will be far from responsive and would rely on the Device Agent checking in. This would result in sub-optimal UX and confusion for the user. How are we to handle this?

This would also affect restart, right?

**Comment by Steve-Mcl** [comment]
> > Additionally, in the case of there being no MQTT broker (i.e. when the device agent is using HTTP polling) these operations will be far from responsive and would rely on the Device Agent checking in. This would result in sub-optimal UX and confusion for the user. How are we to handle this?
> 
> This would also affect restart, right?

Correct.

The affect would be delayed operations (anywhere between 1 and `n` secs - where `n` is the check-in frequency)

**Comment by Steve-Mcl** [comment]
We _might_ be able to determine if the device agent is using HTTP polling and support these operations but inform the user that the operation will occur "next time the device checks in" - not great but potentially feasible?  Not 100% sure i like this approach as there are then new considerations like _how would a user know the device is to be stopped_, _what if the device is currently off-line_, _what if a new command was issued before the previous command_ etc.

**Comment by joepavitt** [comment]
> simply adding the Actions button is what I had in mind.

Agreed. Should be consistent with Instances as much as possible.

> The affect would be delayed operations (anywhere between 1 and n secs - where n is the check-in frequency)

What is the check-in frequency configured as?

> Not 100% sure i like this approach as there are then new considerations like how would a user know the device is to be stopped, what if the device is currently off-line, what if a new command was issued before the previous command has been carried out etc.

Can we get response confirmation that the action has been taken, show the user a notification. So we separate:

1. Action Requested
2. Action Taken

As notifications and in the audit log?

**Comment by knolleary** [comment]
> We might be able to determine if the device agent is using HTTP polling and support these operations but inform the user that the operation will occur "next time the device checks in" - not great but potentially feasible?

We already face this issue with the Device Editor. The device editor only works if the device is connected via MQTT - otherwise the attempt to enable the editor times out. 

I suggest we prioritise effort on the MQTT case initially. The commands will time out if the device isn't connected - a scenario that needs to be handled regardless.

**Comment by Steve-Mcl** [comment]
> > The affect would be delayed operations (anywhere between 1 and n secs - where n is the check-in frequency)
> 
> What is the check-in frequency configured as?

It is configurable but has `defaultValue: 30`

<br>

> > Not 100% sure i like this approach as there are then new considerations like how would a user know the device is to be stopped, what if the device is currently off-line, what if a new command was issued before the previous command has been carried out etc.
> 
> Can we get response confirmation that the action has been taken, show the user a notification. So we separate:
> 
> 1. Action Requested
> 2. Action Taken
> 
> As notifications and in the audit log?

Notifications when user has navigated away are _more difficult_ 

As for audit events, this is feasible but not (currently) scoped out. If Audit log entries are the way to go, it would be good to have these listed and in the acceptance criteria.

But yes, the MQTT comms path has a promisified "send and await reply" so on MQTT enabled systems and where the device agent actually has the broker details set and the device is online, these would be waitable (confirmable) actions.  However that is a fair few ifs+buts.

**Comment by joepavitt** [comment]
Okay, first iteration, let's just it implemented as specified - no need for notifications on confirmation in HTTP mode, etc. 

In the notification on-action, let's try and be as informative/useful as possible:

> _Action Here_ request has been sent to the device requested.

on both occasions still covers I think? If we can easily determine that we're in HTTP polling mode, then let's add an additional note to that along the lines of:

> Note, for devices connected via HTTP polling, there may be a delay in this action taking place.

I'm okay with the delay being in there as a first pass. For FF Cloud, this won't be an issue. If customers raise concern/confusion in self-hosted, we can spend more time on this to address it.

**Comment by Steve-Mcl** [comment]
> > Note, for devices connected via HTTP polling, there may be a delay in this action taking place.
> 
> To be clear, I'm suggesting we only provide this functionality for MQTT connected clients and not try to solve it for HTTP-only clients today.

Are you suggesting the UI actions element would simply be hidden for HTTP polling devices OR fire and forget (HTTP polling devices simply wont do anything)?

_We can determined if FF is setup for MQTT but I am not sure we know (in FF) if the device has MQTT connection details in its yaml?_


---

To try and get clarity, are we proposing:

1. If FF is configured for MQTT, we always show the actions dropdown on all devices
1. If FF is NOT configured for MQTT, we do not show the actions dropdown on any device
1. BONUS:  If we can (easily) determine the device is using HTTP, we hide the actions dropdown for device?

**Comment by joepavitt** [comment]
> If FF is NOT configured for MQTT, we do not show the actions dropdown on any device
> BONUS: If we can (easily) determine the device is using HTTP, we hide the actions dropdown for device?

Aren't these the same? If not MQTT, don't show the actions?

**Comment by Steve-Mcl** [comment]
> Aren't these the same? If not MQTT, don't show the actions?

A platform can have MQTT enabled and a device _can_ be legacy without the broker config.

Item 2 is referring to when the platform has NOT enabled MQTT
Item 3 is referring to when the platform HAS enabled MQTT but the device is using HTTP polling (for example legacy device)

**Comment by Steve-Mcl** [comment]
PR raised in draft state while I get final clarity on UX:

As it stands, the Action Dropdown is always visible and actions are available depending on reported state (same as instance). 

* Actions executed against an offline device will result in no response and thus a timeout & toast "Restart request timed out: no response from device."
* Actions executed when the device agent is not updated will result in no response and thus a timeout & toast "Restart request timed out: no response from device."
* Actions executed when device comms are not configured will toast a message "Actions are not available" (the console log will reveal a more technical explanation of `response: { data: { code: 'no_device_comms', error: 'Actions are not available' }}}`


For discoverability of this feature, it is good since regardless of Device Agent version and FF Device comms being configured.  However I would understand if the UX was undesirable to some.  for example: We could permit the Actions to be operable but state more clearly why it is not working (e.g. "Device Agent needs updating to latest version", "Device Comms should be configured for the platform and the device").  Alternatively, we could disable or hide the Actions Dropdown based on Agent Version and/or Platform Device comms not being setup - but that would mean the feature is less discoverable.

Please advise.

**Comment by Steve-Mcl** [comment]
> > We could permit the Actions to be operable but state more clearly why it is not working (e.g. "Device Agent needs updating to latest version"
> 
> Makes sense, "Device Agent needs updating to version X.X"

@MarianRaphael as the work was paused awaiting this feedback, I can do it this now instead of raising a separate issue.

the reason I paused and awaited this feedback was in case the response resulted in structural or doc changes.

so, in short, I can simply add these small tweaks now and save generating additional issues and PRs?

Up to you.

**Comment by MarianRaphael** [comment]
>  I can simply add these small tweaks now

Great!

**Comment by knolleary** [comment]
Reflecting a comment I just made on the PR for this item, I have a big concern over the 'suspend' behaviour being introduced. We want a consistent user experience between instances and devices. A suspended instance does not get billed. What is the expectation of a suspended device?

The implementation in #3548 will cause the device agent to stop Node-RED, but it remains billable.

**Comment by joepavitt** [comment]
> What is the expectation of a suspended device?

What would be the difference between a stopped/suspended device?

**Comment by knolleary** [comment]
@joepavitt from what I see, we haven't added a 'stop' action - because we don't provide a 'stop' action for instances.

If we wanted to get something shipped in 2.2, we could remove start/suspend and deliver just 'restart' which aligns with the original request. We can then figure out the semantics of suspend for a device and follow up.

**Comment by joepavitt** [comment]
> If we wanted to get something shipped in 2.2, we could remove start/suspend and deliver just 'restart' which aligns with the original request. We can then figure out the semantics of suspend for a device and follow up.

Let's do that

@MarianRaphael can then scope out what a Suspend, etc. look like as this story does encapsulate that action.
