### ISSUE TITLE
Audit log event “Flow Deployed” for Devices

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#3357]
### Description

Introduce a way to publish an Audit log Event from a Device to the FlowFuse Device Audit log.

## Scope

- Devices can publish Audit log events.
- Upon deployment, an Audit log will be generated titled “Flow Deployed” (see Audit log  event of Instances).

### Which customers would this be available to

Everyone - CE/Starter/Team/Enterprise

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

### Acceptance Criteria

- [ ] All log Auditable Log events are triggered in a Node-RED Device that is connected to the platform and are displayed in FF Device Audit Log with correct Node-RED icon and a subtitle under the appropriate log entry heading
   - [ ] flows deployed (full, flows, nodes)
   - [ ] flows reloaded
   - [ ] context key deleted
   - [ ] node-red logged out
   - [ ] Node-RED Settings Updated
- [x] Changelog entry is written up for website
      * https://github.com/FlowFuse/website/pull/1638

**Comment by Steve-Mcl** [comment]
@MarianRaphael 

While implementing this I noted there was no infrastructure for sending the Node-RED generated audit events like there are in the project/instance node-reds - contrary to what I believed when reading the comments of issue #3268 - I (wrongly) assumed since this Issue was asking for the addition of 1 more thing (Flow Deployed) that the pathway to capture node-red raised audit entries was already in-place - this is not the case.

So, in introducing this pathway we automatically get additional audit log entries (on top of just "Flow Deployed")

This left me 2 choices:
1. add code to agent to prevent anything but 'flows deployed"
2. add code to FF core for visualising the additional node-red events

I guess I am asking is it OK that we keep all logging so as to align the device agent with the instance node-reds and accept the same level of audit logging?

It is my strong preference to keep all of the device generated audit entries and thus achieve parity between devices & instances.

**Comment by MarianRaphael** [comment]
For this iteration, it is just about, as you mentioned:

1. The infrastructure for sending audit events generated by devices.
2. The "Flow Deployed" event
(see scope)

In a later iteration, we could add more events if there is a user demand for them.

**Comment by MarianRaphael** [comment]
After further explanation and discussion, it has been determined that since the audit logs are already generated on the device but not transmitted to the FF platform, it would require additional code and effort to stop the existing events from being sent. Therefore, we can simply replicate the behavior of instances to avoid extra work on the Launcher side.

**Comment by Steve-Mcl** [comment]
@MarianRaphael I updated the OP to include acceptance criteria - please revise as you see fit.

I also added a task for Change Log - however, does this actually warrant a changelog entry 🤔

**Comment by MarianRaphael** [comment]
Yes a changelog entry would be great
