### ISSUE TITLE
Implementation - Automated Snapshot creation on Flow Deployment for Devices

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#3358]
### Description

This feature introduces an automated snapshot creation system triggered by the generation of an "Flow Deployed" audit log entry. Each snapshot will be automatically named with the prefix [auto], followed by the current date and time. This feature includes a number of auto snapshots retained; older snapshots beyond this limit will be automatically deleted, provided they are not currently in use as target snapshots.

## User Story
https://github.com/FlowFuse/flowfuse/issues/2423

## Scope

- Trigger Condition: Snapshot creation occurs upon the generation of an "Flow Deployed" audit log entry.
- Naming Convention: Snapshots will be named following the format [auto]Date+Time, incorporating the date and time of creation.
- The maximum number of auto snapshots retained is 10.
- Snapshot Retention: Snapshots currently designated as target snapshots will be exempt from automatic deletion.
- For Devices only

### Which customers would this be available to

Team + Enterprise Tiers (EE)

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate
```[tasklist]
### Requirement
- [ ] https://github.com/FlowFuse/flowfuse/issues/3357
```

**Comment by Steve-Mcl** [comment]
@MarianRaphael please clarify

Is this for Application assigned devices only (or am I to do the work for instance assigned devices too)?

**Comment by MarianRaphael** [comment]
For Application assigned devices only

**Comment by Steve-Mcl** [comment]
@MarianRaphael 

> Naming Convention: Snapshots will be named following the format [auto]Date+Time, incorporating the date and time of creation

Do we want to consider a unified format?

![Image](https://github.com/FlowFuse/flowfuse/assets/44235289/3fa651fb-004d-418a-b1cd-7b85eb3a2be1)


The pipelines snapshot look like this

![Image](https://github.com/FlowFuse/flowfuse/assets/44235289/3ffde963-c1d0-4dbd-b507-63b1d2e72909)

**Comment by Steve-Mcl** [comment]
@knolleary @MarianRaphael 

The `ProjectSnapshots` table expects a valid `UserId` (though it does accept `null` )

Since the snapshot is _kinda_ generated by the system (in response to a flows deploy audit log entry), we dont have a user to set against the snapshot. 

Is this a blocker? 
Should we look to first update auth routines on device agent to report the logged in user back to FF in the API calls?
Perhaps we should we fake it and put a System user in the missing icon? Other?

Attached is what we get when I `null` the user field

![Image](https://github.com/FlowFuse/flowfuse/assets/44235289/6efe1ce3-5e08-4ed7-a0a0-92525c0ad575)

**Comment by Steve-Mcl** [comment]
@knolleary @MarianRaphael 

Performing the Auto Snapshot in the endpoint may be detrimental to the user experience.
1. Consideration of slow device network (and large flows) should be made
2. excessive internet traffic (every deploy is effectively doubled)
   * see recent thread: https://discourse.nodered.org/t/bandwith-consumptions-when-doing-development-through-the-tunnel/85309
3. May eventually block the endpoint?


Based on the above, should we consider:
1. user ability to enable/disable the feature?
1. alternative trigger (e.g. nightly/timed instead of upon each deploy)
1. threaded operation (like a worker/job queue so that we dont sit on the endpoint thread)
1. debounce (e.g. not back up after every single deploy - less wasteful)

**Comment by Steve-Mcl** [comment]
One more. 

I suspect it may be time we add an actual flag/enum to the snapshot table so that we can identify the type. Currently we use name matching regex for pipeline snapshots this issue is suggesting another. 

Should we bite the bullet here?

**Comment by MarianRaphael** [comment]
> Consideration of slow device network (and large flows) should be made

Good point Steve. I initially thought we wouldn't need a configuration, but given the current discussion, it seems pertinent. Could you add a checkbox in the "Developer Mode" settings? By default, it should be enabled, but it should be possible to change it, especially in low bandwidth scenarios

**Comment by gdziuba** [comment]
Could flow snapshots be stored locally on the device instead of immediately sent back to the platform?  Call it a temporary backup?

**Comment by Steve-Mcl** [comment]
GH UI not permitting me to link issue to the dev branch! 

Posting here instead: https://github.com/FlowFuse/flowfuse/tree/3358-device-auto-snapshot

**Comment by Steve-Mcl** [comment]
@MarianRaphael 

> Could you add a checkbox in the "Developer Mode" settings?

what are the RBACS for enabling/disabling auto snapshots?

**Comment by MarianRaphael** [comment]
@Steve-Mcl 
Member

**Comment by Steve-Mcl** [comment]
Verified on staging.



![Image](https://github.com/FlowFuse/flowfuse/assets/44235289/aa78cb40-5479-45e1-8a1c-9393575bc9ce)



![Image](https://github.com/FlowFuse/flowfuse/assets/44235289/3c9c6606-262b-4ac3-9125-6337a8129421)



![Image](https://github.com/FlowFuse/flowfuse/assets/44235289/c6db5a5f-b1c2-43b9-9fd0-8ffe8fae4c6f)




![Image](https://github.com/FlowFuse/flowfuse/assets/44235289/2ff76e62-3b35-4c79-aa3a-ca1ab4f8874c)
