### ISSUE TITLE
Application bound Devices in Starter team are getting Project Nodes installed

### ISSUE THREAD

**Issue by hardillb** [FlowFuse/flowfuse#3560]
### Current Behavior

As title:

Application bound Devices in Starter team are getting access to the Project Nodes installed and Device Editor. These are things that should only be available to Team/Enterprise level teams.

### Expected Behavior

Starter Teams should not have access to Project Nodes at all
~Starter Teams should not have access to Device editor~

### Steps To Reproduce

Create new Starter team on staging or production
Create application
Create new device and assign to application
Start Device

### Environment

- FlowFuse version: 2.1.1
- Node.js version: 18.x
- npm version: 9.x
- Platform/OS: Cloud
- Browser: All

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by MarianRaphael** [comment]
See: https://github.com/FlowFuse/CloudProject/issues/374

**Comment by knolleary** [comment]
I believe the scope of this issue is specifically the Project Nodes. The Device Editor access is okay as-is.

**Comment by Steve-Mcl** [comment]
My proposal is as follows:

1. FF Core: Add feature flags to the settings object sent in `GET /api/v1/devices/:deviceId/live/settings`
    1. this is returned in the settings object via a call to `getSettings()` in the agent
2. Device-agent: In the launcher add `featureEnabled` boolean to the `projectLink` object. 
   1. This flag, `featureEnabled` will fail safe to `true` 
   1. This will be available in `RED.settings.flowforge.projectLink` on the project nodes
   1. Condition value the written to  `.projectLink.broker.url`,  `.projectLink.broker.username` and  `.projectLink.broker.password` based on `featureEnabled` (set them to empty string if `featureEnabled === false`)
4. nr-project-nodes: determine the state of the feature and enable project nodes as required
   1. Use a fail safe test (defaults to true) of `const featureEnabled = RED.settings.flowforge.features?.projectComms !== false` to determine if the feature is enabled/inhibited
      1. NOTE: There are other logic tests in place that determine if the project nodes are even loaded as a dependency in the first place. These will **not** change. This change will only determine if, when loaded, if the project nodes are avaiable to the devices tier and will inhibit any attempt to connect to the platform and display a suitable status/warning to the user.
   1.  Permit the nodes to load as before but if feature flag === false, then only partially enable the project nodes. Enough for them to load and display a well worded status (see screenshot)


### Expectations
* If the user updates a device (i.e. causes npm install) and they get the new project nodes, they will appear to connect as before (no change since platform is not updated and flags are not sent).
* If the user updates device-agent, the feature flags will be passed through and project nodes will report the unavailability as per screenshot
* If the platform is not updated, the feature flags will not be presented to device-agent and the fail safe logic will continue to perform as before.
* If the platform is updated, but not the device-agent, the flags WILL be updated in the project settings file but will not be written to the launcher settings so will continue to function as before.

![image](https://github.com/FlowFuse/flowfuse/assets/44235289/0b6b769c-20c8-45f9-a33f-04c3ade465a0)

**Comment by hardillb** [comment]
Verified on Staging
