### ISSUE TITLE
Update links to point to new /editor/<tab> view for Instances

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#3658]
**Depends on:** https://github.com/FlowFuse/flowfuse/issues/3656

In the [original issue](https://github.com/FlowFuse/flowfuse/issues/3656), the `/editor` view was added, but not made the default view. Here, whenever a user clicks an instance in the "Applciations" or "Instances" view, that button should navigate to the new "Editor" view.

**Comment by sherbastian** [comment]
covered by  Add new /instance<instance-id>/editor view #3656

**Comment by joepavitt** [comment]
This isn't covered

**Comment by sherbastian** [comment]
We can cover the removal of the button in https://github.com/FlowFuse/flowfuse/issues/3657.

I agree on the too many clicks issue but we don't have access to the nr-launcher version on the  main "Instances" and "Applications" and we need it in order to know what editor to open (immersive/default).

I think this will hinder us for quite some time, especially when fully transitioning to the immersive editor.

**Comment by cstns** [comment]
I had a discussion with @hardillb about this feature, and we could leave the open editor button in place in the main Instances and Applications view but would need some additional work to get the nr-launcher version on that page.

It would involve some more time to be put in to this task but I think it's worth the effort because the alternative workflow is sub optimal involving too many clicks for navigation.

I would also like to add, on the same page, an "Actions" button (the same as on the instance overview page) to allow users to "mass assign" instance states from a single place.

Additional thoughts are more than welcomed
