### ISSUE TITLE
Design for Flow Viewer in Product

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#3768]

**Comment by joepavitt** [comment]
Not sure this requires too much over-thinking. I've included, in multiple designs before, the concept of an "eye" icon, which, when clicked, opens a modal with the flow viewer and associated tabs/subflows.

**Comment by joepavitt** [comment]
Renamed the issue to generalise it, as it's not scoped to _just_ Snapshots - see full list here: https://github.com/FlowFuse/flowfuse/issues/3623

This design task should relate to a common design pattern that we use in order to make accessible the "flow viewer".

In some cases, e.g. Team Library, there is likely benefit of the viewer being the default view, and then the "code" view being the modal/popup/secondary view.

**Comment by joepavitt** [comment]
For example, on a Blueprint:

Option 1:
<img width="611" alt="Screenshot 2024-04-25 at 10 13 40" src="https://github.com/FlowFuse/flowfuse/assets/99246719/29ecb8bd-6771-4a62-bba5-1bcb0976cbfe">

Option 2:
<img width="597" alt="Screenshot 2024-04-25 at 10 14 00" src="https://github.com/FlowFuse/flowfuse/assets/99246719/7ae794e9-17e8-4e65-88d2-3b4a00a86c1a">

**Comment by joepavitt** [comment]
Very crude modal example:

<img width="1379" alt="Screenshot 2024-04-25 at 10 19 27" src="https://github.com/FlowFuse/flowfuse/assets/99246719/d3f6f2a7-cde4-4424-92b1-2cde7d34a3bd">

**Comment by MarianRaphael** [comment]
Like It! Great

**Comment by cstns** [comment]
Is there an icon for option 2? I found an eye heroicon that would fit option 1 but couldn't find one for the latter in figma or heroicons

**Comment by joepavitt** [comment]
It's in the source code as `/frontend/src/components/icons/Projects` - never got renamed when we did the purge of Project > Instance
