### ISSUE TITLE
Allow direct linking to Create Instance view with blueprint pre-selected

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#3946]
Pre-requisite for https://github.com/FlowFuse/flowfuse/issues/3917

It should be possible to have a url that opens the create instance view with a particular blueprint pre-selected.

This would enable the marketing website to provide 'try this blueprint' button without requiring the user to reselect the blueprint.

The normal create instance form url includes the team slug. We would need a URL that doesn't include a team slug, which can then redirect to the user's default team create instance page.

There are two scenarios:

1. user is already logged in. Can go straight to create form for their *default* team.
2. user is not logged in. Should redirect once they log in
3. user has no account. Not quite sure if we would be able to redirect after account creation *and* email verification steps... that's a lot of steps to get through
```[tasklist]
### MVP
- [ ] https://github.com/FlowFuse/flowfuse/issues/3973
- [x] Unauthenticated users should be redirected to the try blueprint page after authenticating successfully
- [ ] https://github.com/FlowFuse/flowfuse/issues/3999
```

```[tasklist]
### Follow On Tasks
- [ ] https://github.com/FlowFuse/flowfuse/issues/3974
```

**Comment by cstns** [comment]
We could leverage the browser's localStorage to store any required data and redirect the user after completing all signup steps.

**Comment by cstns** [comment]
I'll add a series of tasks so we can split this feature into atomic deliverable chunks.

**Comment by cstns** [comment]
Would also like to offer the user the possibility to select the team where to use the blueprint. This could be done after the gross of the implementation is done.

**Comment by cstns** [comment]
Pre-selecting blueprints will always be pointing to an existing blueprint so it can safely be a GET request as it eases implementation as opposed to https://github.com/FlowFuse/flowfuse/issues/3917 deploy flows functionality where we are somewhat forced to use POST in order to avoid url length restrictions.

Given that the GET request will be somewhat visible/customer facing should we pay attention to how the route will look like? Should consider SEO even though the FF app is behind an auth wall and also an SPA?

I'm going with `<FlowFuse.domain>/instance/create?blueprintId=<xxx>` for development purposes but `/blueprint/use` / `blueprint/try/` variations would make more sense if links pointing back th the FF app are relevant.

@knolleary, any thoughts?

**Comment by joepavitt** [comment]
Will close this as the primary tasks are complete, #3974 is a follow on task that can be scheduled in it's own time
