### ISSUE TITLE
Setup shows misleading validation on user name

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/flowfuse#4229]
### Current Behavior

when running first setup, entering a name like **Steve** results in validation error "Username unavailable" 

![chrome_akN5ETWX6z](https://github.com/user-attachments/assets/8add5bcc-7de1-41f4-8dd8-7fa286866e0e)

### Expected Behavior

Shoud either simply accept and auto-lowercase the name OR the validation should state "Lowercase letters only" (or similar)

### Steps To Reproduce

enter setup, enter a mixed case username

### Environment

- FlowFuse version: Current Git (2.6.x)
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
Should help with https://github.com/FlowFuse/flowfuse/issues/3839

**Comment by joepavitt** [comment]
We have this pattern for the instance name:

<img width="590" alt="Screenshot 2024-07-19 at 18 59 41" src="https://github.com/user-attachments/assets/6c62a127-e7f4-49d4-b2ed-6d3081e04f65">

but this feels more important that the user notices - as they'll use it to login soon after, if they miss a message, and under the covers we've changed their usernames - that's not good.

So, I think we need to do a check against the username client-side, if contains a capital letter - flag it explicitly so that the user can correct for it.

**Comment by Steve-Mcl** [comment]
> So, I think we need to do a check against the username client-side, if contains a capital letter - flag it explicitly so that the user can correct for it.

Not sure we need to be so forceful Joe. 

The Reason I say that is because I can create a lowercase username then sign in with mixed case or all uppercase if I want to. It is accepted as is right now. 

So it may just be that we need to implicitly lowercase the user's input & sign them up.
