### ISSUE TITLE
Re-open NR Editors in New Tab

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#4727]
### Description

We've had enough feedback from users RE; our change with the "Immersive Editor", that we should now action it. Currently, the Immersive Editor opens in the same tab as the FlowFuse Editor. 

Moving forward, any "Open Editor" buttons should open that Immersive Editor in a new tab.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Steve-Mcl** [comment]
> Moving forward, any "Open Editor" buttons should open that Immersive Editor in a new tab.

Um. yuk?
Are we sure that is _really_ what is wanted?

Personally, I dislike immersive mode and as per previous customer request, clicking the "Open Editor" using CTRL (or middle click) was correctly implemented - to open non-immersive in a new tab.


Perhaps we need to bite the bullet and provide a choice?

**Comment by Steve-Mcl** [comment]
PS, as it happens, I have found the current implementation is not quite standard (i.e. try right clicking the button for choosing "Open in new tab or open in new window - it is broken!)  When I did https://github.com/FlowFuse/flowfuse/pull/4800 it was working fine so something has changed since then

**Comment by joepavitt** [comment]
> Are we sure that is really what is wanted?

Yes, the open editor button replacing the FlowFuse UI is the consistent friction that myself, Nick, Rob and many customers have reported. Users are expecting Node-RED editor to open in a new tab, alongside the FlowFuse workflow.

> PS, as it happens, I have found the current implementation is not quite standard (i.e. try right clicking the button for choosing "Open in new tab or open in new window - it is broken!)

It's being fixed: https://github.com/FlowFuse/flowfuse/issues/4836

> Personally, I dislike immersive mode

What about it do you not like?

**Comment by joepavitt** [comment]
Yes, the issue is about ensuring our behaviour is consistent. What are you saying is "broken"? The fact there is no "open in new tab" option?

**Comment by Steve-Mcl** [comment]
> Yes, the issue is about ensuring our behaviour is consistent. What are you saying is "broken"? The fact there is no "open in new tab" option?

It is broken because it seems to be using "mouse up".  

Try right clicking any "normal"/"standard" hyperlink and you get a menu where you (the user) can either dismiss it or you can chose "open in new tab" or "open in new window" etc.

Currently, Right clicking the "Open Editor" button **immediately** opens editor in immersive (in same tab) THEN shows you the rightlick menu. 

It was all working as per expected UX standards following merge of https://github.com/FlowFuse/flowfuse/pull/4800

**Comment by joepavitt** [comment]
@cstns can cover why `mouseup` was required - but good spot on the right-clicking

**Comment by cstns** [comment]
The `@click` event handler doesn't register mouse3 events (middle mouse button click).  @Steve-Mcl showed me earlier the right click issue but now having tried it locally on chrome/ffox didn't replicate it, will need to look into it
