### ISSUE TITLE
Global Search does not return anything for ID or description

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/flowfuse#4806]
### Description

When I have an app, instance or device ID, I would like to be able to find that in the global search like I can in the instance and device search bars.

Additionally, i put descriptions on my devices and applications - would be great if they too were included in the search (like the device and application search bars do currently)

### e.g. functionality present on inner search bars missing from Global Search
![chrome_vrIVf8hxHX](https://github.com/user-attachments/assets/8992f68e-54f1-43c1-9706-919f9011397d)

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate
```[tasklist]
### Tasks
- [ ] https://github.com/FlowFuse/flowfuse/issues/4813
- [ ] https://github.com/FlowFuse/flowfuse/pull/4808
```

**Comment by knolleary** [comment]
I've raised #4808 to add description/type to the search scope.

Adding support for searching by ID needs a bit more work. The application search is done in the frontend - where the all the objects have their hashids available.

We cannot search the database using hashids. So the strategy will need to be, for each object type:
 - Attempt to decode the query string using that objects `decodeHashid` function.
 - If it decodes cleanly, then lookup that specific object and just return it
 - Otherwise fall back to the full search

If a hashid decodes for one model type, we should not try searching the other models. The logic is fairly straight forward, just a bit more fiddly than I can do right now.
